# Generated by Django 5.1.3 on 2024-12-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='category',
            new_name='category_name',
        ),
    ]
